### PR TITLE
comment: check for when take picture is clicked

### PR DESCRIPTION
**Pull request by IEnoobong**

### CODE REVIEW

**Comment by AbdulDroid** [comment]
There is a checker that check if you've taken the picture before that's y I didn't use the take_picture logic again, I wanted to add simplify my life idea to the app

**Comment by IEnoobong** [comment]
But how does it take the picture in the first instance? If there's not picture taken, what is the checker checking against?

**Comment by AbdulDroid** [comment]
I use the `picture_taken` variable to check if picture has being taken, if it has then move to detection, else take the by picture by opening the `NativeModel` `activity` to take the pics

**Comment by AbdulDroid** [comment]
I'll update the `code` like you suggested and add `comments` to help you navigate through it sir

**Comment by IEnoobong** [comment]
>I use the picture_taken variable to check if picture has being taken, if it has then move to detection, else take the by picture by opening the NativeModel activity to take the pics

Oo ok, I understand 

>I'll update the code like you suggested and add comments to help you navigate through it sir

Thank you, let me know when you do 💯

**Pull request merged**
